### ISSUE TITLE
Have you used `cudnn` when you trained your model?

### ISSUE THREAD

**Issue by daa233** [jiangtaoxie/MPN-COV#3]
Hi, Jiangtao.

I was trying to run your example code of training on imagenet from scratch on Ubuntu 14.04, MATLAB R2017a, CUDA8.0 and cudnn v4. But I have encountered the following error when I run `MPN_COV_main` in MATLAB R2017a:
```text
mpn-cov-conv-net/MPN-COV-ConvNet/matlab/src/bits/impl/nnconv_cudnn.cu":120
(CUDNN_STATUS_BAD_PARAM)]

Error in vl_simplenn (line 302)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...

Error in cnn_train>processEpoch (line 340)
    res = vl_simplenn(net, im, dzdy, res, ...

Error in cnn_train (line 134)
    [net, state] = processEpoch(net, state, params, 'train') ;

Error in MPN_COV_main (line 122)
[net, info] = trainFn(net, imdb, getBatchFn(opts, net.meta), ...
```
Could you tell me whether you used `cudnn` library when you trained your model, and if you used, which version you used?

**Comment by jiangtaoxie** [comment]
Our programs are based on MatConvNet-1.0-beta22, so cudnn library needs to be higher than v4. The version we used is v5.1

**Comment by daa233** [comment]
Thank you for your reply. It may caused by the mismatched version of MATLAB and cudnn, but I can run the code without cudnn support.

**Comment by daa233** [comment]
I got away from the problem by switching to a newer version of MatConvNet and cudnn (v6).
